[package]
name = "is-nice"
version = "0.0.69"
edition = "2021"
description = "Tells you whether or not a string is nice."
license = "MIT"

[dependencies]
rstest = "0.16.0"
regex = "1.7.1"
once_cell = "1.17.1"
